main_project/main_app/urls.py
from django.urls import path
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('vconnect/',views.Landingview.as_view(), name="landing"),
    path('signup/',views.signup, name="create_user"),
    path('login/',views.user_login, name="login"),
    path('logout/',views.user_logout, name="logout"),
    path('<int:pk>/hospital_register/',views.NewHospital,name="create_hospital"),
    path('hopsitallist/',views.HospitalListView.as_view(),name="all_hopsital"),
    path('hospital/<int:pk>',views.HospitalDetailView.as_view(),name="detail_hospital"),
    path('place_request/<int:pk>',views.RequestCreateView.as_view(),name="request_hospital"),
    path('received_reqs/<int:pk>',views.RequestsReceivedDetailView.as_view(),name="request_received"),
    path('asked_reqs/<int:pk>',views.RequestsAskedDetailView.as_view(),name="request_asked"),
    path('approve_req/<int:pk>',views.ApproveRequest,name="approve_request"),
    path('decline_req/<int:pk>',views.DeclineRequest,name="decline_request"),
    path('citizen_detail/<int:pk>',views.CitizenDetailView.as_view(),name="citizen_detail"),
    path('get_covid_data/<int:pk>',views.PredictCovid,name='predict_covid'),
    path('citizen_update/<int:pk>',views.CitizenUpdateView.as_view(),name="citizen_update"),
    path('addToWatchlist/<int:pk>',views.AddToWatchlist,name="citizen_watchlist"),
    path('UserWatchlist/<int:pk>',views.CitizenWatchListView.as_view(),name="citizen_watchlist_hospital"),
    path('predict/',views.getPredictions,name='predict'),
    path('hospital_update/<int:pk>',views.HospitalUpdateView.as_view(),name='hospital_update'),
    path('update_cases/',views.DateCaseCreateView.as_view(),name='hospital_update_form'),
    path('approve_mail/<int:pk>',views.sendApprovalMail,name="approve_mail"),
    path('add_comment_form/<int:pk>',views.AddCommentCreateView.as_view(),name="add_comment_form"),
    path('daily_cases',views.DailyCasesTemplateView.as_view(),name="daily_cases"),



]

main_project/main_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_project/main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from main_app.models import Hospital,UserModel,RequestModel,DateCaseModel,CitizenModel,ReviewModel


class HospitalForm(forms.ModelForm):

    class Meta():
        model = Hospital
        fields = ('name','address','beds','oxygen_cylinders','wards','curr_patients')

class CitizenForm(forms.ModelForm):

    class Meta():
        model = CitizenModel
        fields = ('gender','is_cough','is_fever','is_sore_throat','is_shortness_of_breath','is_head_ache','is_age_60_and_above','is_contact')

class DateCaseForm(forms.ModelForm):

    class Meta():
        model = DateCaseModel
        fields = ('date','cases')

class RequestForm(forms.ModelForm):

    class Meta():
        model = RequestModel
        fields = ('beds_requested','oxygen_cylinders_requested','contact_email','contact_phone')

class UserForm(forms.ModelForm):
    password  = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class UserExtraForm(forms.ModelForm):

    class Meta():
        model = UserModel
        fields = ('unit','unit_name')

class ReviewForm(forms.ModelForm):
    class Meta():
        model = ReviewModel
        fields = ('comments','rating')

main_project/main_app/views.py
from django.shortcuts import render,get_object_or_404,redirect
from main_app.forms import HospitalForm,UserForm,UserExtraForm,RequestForm,DateCaseForm,CitizenForm,ReviewForm
from main_app.models import Hospital, UserModel, RequestModel, DateCaseModel, CitizenModel,ReviewModel
from django.views.generic import TemplateView,CreateView,ListView,DetailView,UpdateView
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy,reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import date
import joblib
import smtplib
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.
class Landingview(TemplateView):
    template_name = "landing.html"

class DailyCasesTemplateView(TemplateView):
    template_name = "daily_cases.html"

class HospitalListView(ListView):
    model = Hospital
    context_object_name = 'hospitals'
    template_name = 'hospital_list.html'

    def get_queryset(self):
        order = self.request.GET.get('orderby', '-beds')
        return Hospital.objects.order_by(order)

    def get_context_data(self, **kwargs):
        context = super(HospitalListView, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby')
        return context

class HospitalDetailView(DetailView):
    model = Hospital
    template_name = 'hospital_detail.html'
    context_object_name = 'curr_hospital'

    def get_context_data(self, **kwargs):
        # hosp_id = self.kwargs.get('pk')
        # hospital_curr = get_object_or_404(Hospital,pk=hosp_id)
        # print(hospital_curr.beds)
        print(self.request.user)
        context = super(HospitalDetailView, self).get_context_data(**kwargs)
        context['form'] = RequestForm
        return context

class HospitalUpdateView(UpdateView):
    model = Hospital
    context_object_name = 'curr_hospital'
    fields = ('beds','oxygen_cylinders','wards','curr_patients')
    template_name = 'update_hospital.html'

class RequestCreateView(CreateView):
    model = RequestModel
    form_class = RequestForm

    def form_valid(self,form):
        hosp_id = self.kwargs.get('pk')
        hospital_curr = get_object_or_404(Hospital,pk=hosp_id)
        # print(hospital_curr.beds)
        new_request = form.save(commit=False)
        # new_request.name = self.request.user.user_profile.unit_name
        new_request.name_requested = self.request.user.user_profile.assigned_hospital.name
        new_request.name_received = hospital_curr.name
        new_request.save()

        hospital_logged = self.request.user.user_profile.assigned_hospital

        hospital_curr.received_requests.add(new_request)
        hospital_logged.asked_requests.add(new_request)
        hospital_curr.save()
        hospital_logged.save()
        # new_request.beds_requested = form.instance.beds_requested
        # new_request.oxygen_cylinders_requested = form.instance.oxygen_cylinders_requested
        # new_request.name =
        return super(RequestCreateView, self).form_valid(form)

class RequestsReceivedDetailView(DetailView):
    model = Hospital
    template_name = 'requests_receive.html'
    context_object_name = 'hospital'

class RequestsAskedDetailView(DetailView):
    model = Hospital
    template_name = 'requests_ask.html'
    context_object_name = 'hospital'

class CitizenDetailView(DetailView):
    model = CitizenModel
    template_name = 'user_detail.html'
    context_object_name = 'citizen'

class CitizenUpdateView(UpdateView):
    model = CitizenModel
    fields = ('is_cough','is_fever','is_sore_throat','is_shortness_of_breath','is_head_ache','is_age_60_and_above','is_contact')
    template_name = 'user_update.html'

class CitizenWatchListView(ListView):
    model = CitizenModel
    template_name = 'user_watchlist.html'
    context_object_name = 'citizen'

    def get_queryset(self):
        order = self.request.GET.get('orderby', '-beds')
        return Hospital.objects.order_by(order)

    def get_context_data(self, **kwargs):
        context = super(CitizenWatchListView, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby')
        return context

def AddToWatchlist(request,pk):
    hospital = get_object_or_404(Hospital,pk=pk)
    citizen = request.user.user_profile.assigned_citizen
    citizen.watchlist.add(hospital)
    citizen.save()

    return redirect('main_app:citizen_detail',pk=citizen.pk)

def PredictCovid(request,pk):
    citizen = get_object_or_404(CitizenModel,pk=pk)
    citizen.get_prediction()
    citizen.save()
    # print('here')
    return redirect('main_app:landing')

def ApproveRequest(request,pk):
    Request = get_object_or_404(RequestModel,pk=pk)
    Hospital = request.user.user_profile.assigned_hospital

    Request.approve_request()
    Hospital.beds = Hospital.beds - Request.beds_requested
    Hospital.oxygen_cylinders = Hospital.oxygen_cylinders - Request.oxygen_cylinders_requested
    Hospital.save()

    return redirect('main_app:landing')

def DeclineRequest(request,pk):
    Request = get_object_or_404(RequestModel,pk=pk)
    Request.decline_request()

    return redirect("main_app:landing")


@login_required
def NewHospital(request,pk):
    main_user = get_object_or_404(User,pk=pk)
    hospital_made = False
    if hasattr(main_user.user_profile,'assigned_hospital'):
        hospital_made = True

    if request.method == 'POST' and hospital_made==False:
        hospital_form = HospitalForm(data=request.POST)
        datecase_form = DateCaseForm(data=request.POST)

        if hospital_form.is_valid() and datecase_form.is_valid():
            hospital = hospital_form.save(commit=False)
            hospital.user = main_user.user_profile
            hospital.save()

            datacase = datecase_form.save(commit=False)
            datacase.hospital = hospital
            datacase.save()

        else:
            print(hospital_form.errors,datacase.errors)

    else:
        hospital_form = HospitalForm()
        datecase_form = DateCaseForm()

    return render(request,"register_hospital.html",{'hospital_form':hospital_form,'hospital_made':hospital_made,'datecase_form':datecase_form})

def signup(request):

    registered = False
    UnitName = "Connect and Contribute"
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_extra_form = UserExtraForm(data=request.POST)
        citizen_form = CitizenForm(data=request.POST)

        if user_form.is_valid() and user_extra_form.is_valid() and citizen_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            extra = user_extra_form.save(commit=False)
            print(extra.unit)
            extra.user = user

            if extra.unit == 'Hospital':
                print(extra.unit)
                extra.is_Hospital = True
            elif extra.unit == 'Citizen':
                print(extra.unit)
                extra.is_Citizen = True


            extra.save()
            print(extra.unit)
            citizen = citizen_form.save(commit=False)
            citizen.user = user.user_profile
            citizen.save()

            UnitName = extra.unit_name
            registered = True

        else:
            print(user_form.errors,user_extra_form.errors,citizen_form.errors)

    else:
        user_form = UserForm()
        user_extra_form = UserExtraForm()
        citizen_form = CitizenForm()

    return render(request,'signup.html',{'user_form':user_form,'user_extra_form':user_extra_form,
    'registered':registered,'UnitName':UnitName,'citizen_form':citizen_form})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('main_app:landing'))

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse_lazy('main_app:landing'))
            else:
                return HttpResponseRedirect("ACCOUNT NOT ACTIVE")

        else:
            print("Someone Tried to login and failed")
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'login.html')

def getPredictions(request):
    scaled = joblib.load("covidpred.model")
    prediction = scaled.predict_proba([[True,True,True,0,0,0,0,0]])
    result = prediction[0][1]*100
    print(prediction[0][1])
    return render(request,'result.html', {'result':result})


class DateCaseCreateView(CreateView):
    model = DateCaseModel
    form_class = DateCaseForm
    template_name='update_cases.html'

    def form_valid(self,form):
        hospital_curr = self.request.user.user_profile.assigned_hospital
        new_request = form.save(commit=False)
        new_request.save()
        hospital_curr.hospital_case.add(new_request)

        return super(DateCaseCreateView, self).form_valid(form)

def sendApprovalMail(request,pk):

    request_main = get_object_or_404(RequestModel,pk=pk)

    text = 'Greetings from {} \n This is the approval mail for your logistics request. Please get in touch with our Hospital Vconnect Admin to further dicsuss the transfer of logistics \n Email: {}'.format(request.user.user_profile.unit_name,request.user.email)

    send_mail('Approval Mail for Logistics Transfer',text,'vconnectofficialapproval@gmail.com'
    ,[request_main.contact_email],fail_silently=False,)

    return HttpResponseRedirect(reverse_lazy('main_app:landing'))

class AddCommentCreateView(CreateView):
    model = ReviewModel
    form_class = ReviewForm
    template_name='add_comment_form.html'

main_project/main_app/templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
  <title>VConnect</title>
</head>
<body>

  <div class="navbar-main" id="myNavbar">
    <a href="{% url "main_app:landing" %}" class="active">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url "main_app:logout" %}">Logout</a>
    {% else %}
        <a href="{% url "main_app:create_user" %}">Sign Up</a>
        <a href="{% url "main_app:login" %}">Login</a>
    {% endif %}
    {% if user.is_authenticated and request.user.user_profile.is_Citizen %}
        <a href="{% url "main_app:citizen_detail" pk=request.user.user_profile.assigned_citizen.pk %}">User Profile</a>
        <a href="{% url "main_app:citizen_update" pk=request.user.user_profile.assigned_citizen.pk %}">Update Details</a>
    {% endif %}
    <a href="{% url "main_app:all_hopsital" %}">Hospitals list</a>
    <a href="{% url "main_app:daily_cases" %}">Daily-Cases</a>

    {% if request.user.user_profile.assigned_hospital.pk %}
        <a href="{% url "main_app:detail_hospital" pk=request.user.user_profile.assigned_hospital.pk %}">Your Hospital</a>
        <a href="{% url "main_app:request_received" pk=request.user.user_profile.assigned_hospital.pk %}">Requests Received</a>
        <a href="{% url "main_app:request_asked" pk=request.user.user_profile.assigned_hospital.pk %}">My Requests</a>
    {% endif %}
    <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
  </div>

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      {% if user.is_authenticated %}
          {% if request.user.user_profile.is_Hospital %}
              <h1 class="display-4" style="color: azure;">Welcome, <b>{{request.user.user_profile.unit_name}}</b></h1>
              <p class="lead" style="color: azure;">We Value Your Efforts</p>
          {% else %}
              <h1 class="display-4" style="color: azure;">Welcome, <b>{{request.user.username}}</b></h1>
              <p class="lead" style="color: azure;">Please do keep your health status up to date and keep checking the covid-predcictor score.</p>
              <p class="lead" style="color: azure;">Stay up-to-date with hospital's status and them to your watchlist to keep track of them easily</p>
              <p class="lead" style="color: azure;">Stay strong INDIA!</p>
          {% endif %}
      {% else %}
          <h1 class="display-4" style="color: azure;"><b>Login to access all features!</b></h1>
          <p class="lead" style="color: azure;">This is an official portal to imporve coordination between<br>Hospitals and Supply Chains of India to fight the virus more effectively!</p>
      {% endif %}
    </div>
  </div>

  <div id="quote">
      Stay Strong India!
  </div>

  <div class="container">

    {% block content %}
    {% endblock %}

  </div>




  <script src="{% static 'js/main.js' %}"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <script>
      window.onscroll = function() {mySecondFunction()};

      var quote = document.getElementById("quote");
      var sticky = quote.offsetTop;

      function mySecondFunction() {
        if (window.pageYOffset >= sticky) {
          quote.classList.add("sticky")
        } else {
          quote.classList.remove("sticky");
        }
      }

      function myFunction() {
        var x = document.getElementById("myNavbar");
        if (x.className === "navbar-main") {
          x.className += " responsive";
        } else {
          x.className = "navbar-main";
        }
      }

      function activateHospital() {
          var dropdown = document.getElementById("dropdownMenuButton")
          var hosp_form = document.getElementById("hospital_extra")
          var citizen_form = document.getElementById("citizen_extra")

      }

      $(document).ready(function() {
        $('#user-type').change(function(){
          if(this.selectedIndex == 1){
            $('#form_signup').show()
            $('#hospital_extra').show()
            $('#citizen_extra').hide()
          }else if(this.selectedIndex == 2){
            $('#form_signup').show()
            $('#citizen_extra').show()
            $('#hospital_extra').show()
          }else{
            $('#form_signup').hide()
            // $('#hospital_extra').hide()
            // $('#citizen_extra').hide()
          }
        })
      })


      {% block script %}
      {% endblock %}

      {% block covid_cases %}
      {% endblock %}
  </script>

  </body>
</html>

main_project/main_app/templates/main_app/hospital_detail.html
{% extends 'base.html' %}
{% block content %}

<!-- <h6>Name: {{curr_hospital.name}}</h6>
<h6>Beds: {{curr_hospital.beds}}</h6>
<h6>O2 Cyclinders: {{curr_hospital.oxygen_cylinders}}</h6> -->
<table class="my-3 cool-table">
    <tr>
        <th>Name:</th>
        <td>{{curr_hospital.name}}</td>
    </tr>
    <tr>
        <th>Address:</th>
        <td>{{curr_hospital.address}}</td>
    </tr>
    <tr>
        <th>Beds:</th>
        <td>{{curr_hospital.beds}}</td>
    </tr>
    <tr>
        <th>Oxygen Cylinders:</th>
        <td>{{curr_hospital.oxygen_cylinders}}</td>
    </tr>
</table>

  {% if user.is_authenticated and request.user.user_profile.pk != curr_hospital.user.pk %}
      {% if request.user.user_profile.is_Hospital %}
      <div style="margin-bottom: 80px">
        <form class="cool-form" method="POST" action="{% url "main_app:request_hospital" pk=curr_hospital.pk %}">
          {%csrf_token%}
          {{form}}
          <br><br>
          <button type="submit">Request</button>
        </form>
      </div>
      {% endif %}
  {% endif %}

  {% if user.is_authenticated and request.user.user_profile.pk == curr_hospital.user.pk %}
    <a class='btn btn-warning mr-3' href="{% url 'main_app:hospital_update' pk=curr_hospital.pk %}">Update Hospital</a>
  {% endif %}
  {% if user.is_authenticated and request.user.user_profile.pk == curr_hospital.user.pk %}
    <a  class='btn btn-warning mr-3' href="{% url 'main_app:hospital_update_form' %}">Add Daily Cases</a>
  {% endif %}


<div style="margin-bottom: 120px;">
    <canvas id="myChart" width="400" height="100"></canvas>

</div>

{% endblock %}

{% block script %}
    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [{% for item in curr_hospital.hospital_case.all %}'{{item.date}}',{% endfor %}],
        datasets: [{
            label: '# of Votes',
            data: [{% for item in curr_hospital.hospital_case.all %}{{item.cases}},{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
    });
{% endblock %}

main_project/main_app/templates/main_app/hospital_list.html
{% extends 'base.html' %}
{% block content %}
  <h2 class="my-3 text-center">Hospital List</h2>
  <form method="get" action="{% url "main_app:all_hopsital" %}" class="cool-form my-4">
    <p>Total Hospitals: {{hospitals.count}}</p>
    <p>order_by: <input type="text" value={{orderby}} name="orderby"/></p>
    <p><button type="submit" name="submit" value="submit">Submit</button></p>
  </form>
  <div class="row">
    {% for hosp in hospitals %}

            {% if user.is_authenticated and request.user.user_profile.assigned_hospital.pk %}
                {% if request.user.user_profile.assigned_hospital.pk != hosp.pk %}
                    <div class="card mx-1 my-1 col">
                       <div class="card-body">
                         <h5 class="card-title">{{hosp.name}}</h5>
                         <h6 class="card-subtitle mb-2 text-muted"><em>Address</em>: {{hosp.address}}</h6><br>
                         <h6 class="card-subtitle mb-2 text-muted"><em>Beds</em>: {{hosp.beds}}</h6>
                         <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Oxygen Cylinders</em>: {{hosp.oxygen_cylinders}}</h6>
                         <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Wards</em>: {{hosp.wards}}</h6>
                         <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Patients</em>: {{hosp.oxygen_cylinders}}</h6>
                         <div class="card-links pb-1">
                           <a href="{% url "main_app:detail_hospital" pk=hosp.pk %}" class="card-link">Click here to know more</a>
                         </div>
                         {% if user.is_authenticated and  request.user.user_profile.is_Citizen %}
                             <a href="{% url "main_app:citizen_watchlist" pk=hosp.pk %}" class="card-link">Add to watchlist</a>
                         {% endif %}
                       </div>
                     </div>
                 {% endif %}

            {% else %}
                <div class="card mx-1 my-1 col">
                   <div class="card-body">
                     <h5 class="card-title">{{hosp.name}}</h5>
                     <h6 class="card-subtitle mb-2 text-muted">{{hosp.address}}</h6>
                     <h6 class="card-subtitle mb-2 text-muted"><em>Beds</em>: {{hosp.beds}}</h6>
                     <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Oxygen Cylinders</em>: {{hosp.oxygen_cylinders}}</h6>
                     <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Wards</em>: {{hosp.wards}}</h6>
                     <h6 class="card-subtitle mb-2 text-muted mb-3"><em>Patients</em>: {{hosp.oxygen_cylinders}}</h6>
                     <div class="card-links pb-1">
                       <a href="{% url "main_app:detail_hospital" pk=hosp.pk %}" class="card-link">Click here to know more</a>
                     </div>
                     {% if user.is_authenticated and  request.user.user_profile.is_Citizen %}
                         <a href="{% url "main_app:citizen_watchlist" pk=hosp.pk %}" class="card-link">Add to watchlist</a>
                     {% endif %}
                   </div>
                 </div>

            {% endif %}
    {% endfor %}
  </div>
  <div class="my-5">&nbsp</div>
{% endblock %}

main_project/main_app/templates/main_app/requests_receive.html
{% extends 'base.html' %}
{% block content %}

  <h5 class="my-3 text-center">Your received {{hospital.received_requests.all.count}} requests</h5>
  <div class="row d-flex" style="margin-bottom:80px;">
    {% for request in hospital.received_requests.all %}
           <div class="card col-md-4 col-sm-6">
              <div class="card-body">
                <h5 class="card-title">Received from: {{request.name_requested}}</h5>
                <h6 class="card-subtitle mb-2 text-muted"><em>Beds requested</em>: {{request.beds_requested}}</h6>
                <h6 class="card-subtitle mb-2 text-muted"><em>O2 cylinders requested</em>: {{request.oxygen_cylinders_requested}}</h6>
                <h6 class="card-subtitle mb-2 text-muted"><em>Email</em>: {{request.contact_email}}</h6>
                <br>

                {% if request.approved_status %}
                    {% if request.is_approved %}
                        <h5 class="card-subtitle mb-2 text-muted"><b>You approved the request</b></h5>
                        <a type="submit" href="{% url 'main_app:approve_mail' pk=request.pk %}" class="btn btn-outline-success btn-lg btn-block">Send Approval Mail</a>
                    {% else %}
                        <h5 class="card-subtitle mb-2 text-muted"><b>You declined the request</b></h5>
                    {% endif %}
                {% else %}
                        <a type="submit" href="{% url 'main_app:approve_request' pk=request.pk %}" class="btn btn-outline-success btn-lg btn-block">Approve</a>
                        <a type="submit" href="{% url 'main_app:decline_request' pk=request.pk %}" class="btn btn-outline-danger btn-lg btn-block">Decline</a>
                {% endif %}

              </div>
            </div>
    {% endfor %}
  </div>

{% endblock %}

main_project/main_app/templates/main_app/result.html
{% extends 'base.html' %}
{% block content %}

<h1> {{ result }}</h1> 
{% endblock %}

main_project/main_app/templates/main_app/user_watchlist.html
{% extends 'base.html' %}
{% block content %}

  <div class="mt-3"></div>
  <div class="mb-3"></div>
  <h1>{{citizen.gender}}</h1>
  <h1>{{citizen.watchlist.all.count}}</h1>
  <div class="row d-flex" style="margin-bottom:50px;">
    {% for hosp in citizen.watchlist.all %}
           <div class="card col-md-4 col-sm-6">
              <div class="card-body">
                <h5 class="card-title">{{hosp.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{hosp.address}}</h6>
                <h6 class="card-subtitle mb-2 text-muted"><em>Beds</em>: {{hosp.beds}}</h6>
                <h6 class="card-subtitle mb-2 text-muted"><em>Oxygen Cylinders</em>: {{hosp.oxygen_cylinders}}</h6>
                <a href="{% url "main_app:detail_hospital" pk=hosp.pk %}" class="card-link">Click here to know more</a>
                <a href="#" class="card-link">Request</a>
              </div>
            </div>
    {% endfor %}
  </div>

{% endblock %}